In [1]:
import numpy as np
ironman_zeros = np.zeros(10, dtype=int) #建立一個內容為0 長度為10的整數陣列
ironman_ones = np.ones((3,5) ,dtype=float)  #建立一個內容為1 3x5 的浮點數陣列
ironman_empty = np.empty((3,2) )  #建立一個內容為1 3x2 的無初始值陣列
ironman_full = np.full((4,2), 2.2) #建立一個內容為2.2 4x2 的浮點數陣列

print('ironman_zeros---->', ironman_zeros)
print('ironman_ones---->', ironman_ones)
print('ironman_empty---->', ironman_empty)
print('ironman_full---->', ironman_full)

ironman_zeros----> [0 0 0 0 0 0 0 0 0 0]
ironman_ones----> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
ironman_empty----> [[1.89146896e-307 1.37961302e-306]
 [1.00136557e-307 1.95821439e-306]
 [1.33511290e-306 2.22518251e-306]]
ironman_full----> [[2.2 2.2]
 [2.2 2.2]
 [2.2 2.2]
 [2.2 2.2]]


In [2]:
ironman_arange = np.arange(0,20,2) #建立一個依序填滿的陣列 0到20間隔為2
ironman_linspace = np.linspace(0,1,5) #建立一個5個值的陣列，在0到1間平均分布

print('ironman_arange---->', ironman_arange)
print('ironman_linspace---->', ironman_linspace)


ironman_arange----> [ 0  2  4  6  8 10 12 14 16 18]
ironman_linspace----> [0.   0.25 0.5  0.75 1.  ]


In [3]:
ironman_random = np.random.random((3,3)) #建立一個3*3 陣列，在0到1間亂數值
ironman_ranf = np.random.ranf((5)) #建立一個5 陣列，在0到1間亂數值
ironman_sample = np.random.sample((2,3)) #建立一個323 陣列，在0到1間亂數值

print('ironman_random---->', ironman_random)
print('ironman_ranf---->', ironman_ranf)
print('ironman_sample---->', ironman_sample)

ironman_random----> [[0.1306738  0.81880978 0.46849706]
 [0.57292279 0.97362346 0.16369818]
 [0.64699938 0.23129952 0.10234093]]
ironman_ranf----> [0.03304555 0.01862574 0.25015369 0.73149627 0.76281449]
ironman_sample----> [[0.00898121 0.18074926 0.36402533]
 [0.91982908 0.18223066 0.75602241]]


In [4]:
ironman_normal = np.random.normal(0,1,(3,3)) #建立一個3*3陣列，內容為常態分佈的亂數值 平均0，標準差1
print('ironman_normal---->', ironman_normal)

ironman_normal----> [[ 0.19162232 -1.36309759 -0.00226005]
 [ 0.04943918  1.50674263  0.58402828]
 [-0.6549015  -0.96597353  1.19726421]]


In [5]:
ironman_randint = np.random.randint(0,10,(3,3)) #建立一個3*3陣列，內容介於0到10的整數
print('ironman_randint---->', ironman_randint)

ironman_randint----> [[3 8 9]
 [3 1 4]
 [5 3 8]]


In [6]:
ironman_x1 = np.random.randint(10, size=6)    #一維陣列
ironman_x2 = np.random.randint(10, size=(3,4))     #二維陣列
ironman_x3 = np.random.randint(10, size=(2,3,2))   #三維陣列

print("ironman_x1---->", ironman_x1)
print("ironman_x2---->", ironman_x2)
print("ironman_x3---->", ironman_x3)


ironman_x1----> [9 6 2 7 4 4]
ironman_x2----> [[5 2 4 3]
 [5 1 6 6]
 [1 6 6 6]]
ironman_x3----> [[[3 4]
  [7 1]
  [4 9]]

 [[7 3]
  [2 3]
  [7 6]]]


In [6]:
print("ironman_x1 ndim:     ", ironman_x1.ndim)
print("ironman_x2 ndim:     ", ironman_x2.ndim)
print("ironman_x3 ndim:     ", ironman_x3.ndim)

ironman_x1 ndim:      1
ironman_x2 ndim:      2
ironman_x3 ndim:      3


In [7]:
print("ironman_x1 shape:     ", ironman_x1.shape)
print("ironman_x2 shape:     ", ironman_x2.shape)
print("ironman_x3 shape:     ", ironman_x3.shape)

ironman_x1 shape:      (6,)
ironman_x2 shape:      (3, 4)
ironman_x3 shape:      (2, 3, 2)


In [8]:
print("ironman_x1 size:     ", ironman_x1.size)
print("ironman_x2 size:     ", ironman_x2.size)
print("ironman_x3 size:     ", ironman_x3.size)

ironman_x1 size:      6
ironman_x2 size:      12
ironman_x3 size:      12


In [9]:
print("ironman_x1 dtype:     ", ironman_x1.dtype)
print("ironman_x2 dtype:     ", ironman_x2.dtype)
print("ironman_x3 dtype:     ", ironman_x3.dtype)

ironman_x1 dtype:      int32
ironman_x2 dtype:      int32
ironman_x3 dtype:      int32


In [10]:
print("ironman_x1 itemsize:     ", ironman_x1.itemsize)
print("ironman_x2 itemsize:     ", ironman_x2.itemsize)
print("ironman_x3 itemsize:     ", ironman_x3.itemsize)

ironman_x1 itemsize:      4
ironman_x2 itemsize:      4
ironman_x3 itemsize:      4


In [11]:
print("ironman_x1 nbytes:     ", ironman_x1.nbytes)
print("ironman_x2 nbytes:     ", ironman_x2.nbytes)
print("ironman_x3 nbytes:     ", ironman_x3.nbytes)

ironman_x1 nbytes:      24
ironman_x2 nbytes:      48
ironman_x3 nbytes:      48


In [17]:
# 取得陣列值
print("ironman_x1[2]----->", ironman_x1[2])
print("ironman_x2[2,2]----->", ironman_x2[2,2])
print("ironman_x3[1,1,1]----->", ironman_x3[1,1,1])
# 修改陣列值
ironman_x1[2] = 7
ironman_x2[2,2] = 4
ironman_x3[1,1,1] = 3
print("ironman_x1[2]----->", ironman_x1[2])
print("ironman_x2[2,2]----->", ironman_x2[2,2])
print("ironman_x3[1,1,1]----->", ironman_x3[1,1,1])

ironman_x1[2]-----> 9
ironman_x2[2,2]-----> 2
ironman_x3[1,1,1]-----> 5
ironman_x1[2]-----> 7
ironman_x2[2,2]-----> 4
ironman_x3[1,1,1]-----> 3


In [19]:
ironman_x4 = np.arange(10)
print('ironman_x4---->', ironman_x4)
print('ironman_x4[:5]----->',ironman_x4[:5])         # 前面5個元素
print('ironman_x4[5:]----->',ironman_x4[5:])         # index5 之後的元素
print('ironman_x4[4:7]----->',ironman_x4[4:7])       # index 4~(7-1) 的元素
print('ironman_x4[::2]----->',ironman_x4[::2])       # 間隔2的所有元素
print('ironman_x4[1::2]----->',ironman_x4[1::2])     # index1開始 間隔2的所有元素
print('ironman_x4[::-1]----->',ironman_x4[::-1])     # 反轉元素


ironman_x4----> [0 1 2 3 4 5 6 7 8 9]
ironman_x4[:5]-----> [0 1 2 3 4]
ironman_x4[5:]-----> [5 6 7 8 9]
ironman_x4[4:7]-----> [4 5 6]
ironman_x4[::2]-----> [0 2 4 6 8]
ironman_x4[1::2]-----> [1 3 5 7 9]
ironman_x4[::-1]-----> [9 8 7 6 5 4 3 2 1 0]


In [7]:
ironman_x5 = np.random.randint(10, size=(3,4))     #二維陣列
print('ironman_x5---->', ironman_x5)
print('ironman_x5[:2, :3]----->',ironman_x5[:2, :3])         # 取得  2列        3欄
print('ironman_x5[:3, ::2]----->',ironman_x5[:3, ::2])       # 取得  3列        偶數欄
print('ironman_x5[:,0]----->',ironman_x5[:,0])               #取得 所有列      第(0+1)欄
print('ironman_x5[2,:]----->',ironman_x5[2,:])               #取得 第(2+1)列   所有欄


ironman_x5----> [[0 5 5 2]
 [4 0 2 1]
 [5 0 9 4]]
ironman_x5[:2, :3]-----> [[0 5 5]
 [4 0 2]]
ironman_x5[:3, ::2]-----> [[0 5]
 [4 2]
 [5 9]]
ironman_x5[:,0]-----> [0 4 5]
ironman_x5[2,:]-----> [5 0 9 4]


In [8]:
x = np.array([1,2,3])
print('x----->', x)
x_reshape = x.reshape((3,1))         # 透過reshape建立欄向量
print('x_reshape----->', x_reshape)

x-----> [1 2 3]
x_reshape-----> [[1]
 [2]
 [3]]
x.shape-----> (3,)
x_reshape.shape-----> (3, 1)


In [9]:
y = np.array([4,5,6])
print('concatenate----->',np.concatenate([x,y]))    # 串接陣列
print('vstack----->',np.vstack([x,y]))              # 垂直串接
print('hstack----->',np.hstack([x,y]))              # 水平串接

concatenate-----> [1 2 3 4 5 6]
vstack-----> [[1 2 3]
 [4 5 6]]
hstack-----> [1 2 3 4 5 6]


In [11]:
z = np.array([1,2,3,4,5,6,7,8,9])
z1,z2,z3 = np.split(z,[3,5])              # 分割3個陣列 [index 0~(3-1) ] [ index 3~(5-1)] [index (5~end)]
print("z1---->", z1)
print("z2---->", z2)
print("z3---->", z3)
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('vsplit----->',np.vsplit(z,[2]))    # 垂直分割
print('hsplit----->',np.hsplit(z,[2]))    # 水平分割

z1----> [1 2 3]
z2----> [4 5]
z3----> [6 7 8 9]
vsplit-----> [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]
hsplit-----> [array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])]


In [12]:
x = np.array([-2,-1,0,1,-3])
abs(x)

array([2, 1, 0, 1, 3])

In [13]:
theta = np.linspace(0, np.pi, 3)  #建立一個角度的陣列
print("sin()---->", np.sin(theta))
print("cos()---->", np.cos(theta))
print("tan()---->", np.tan(theta))

sin()----> [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos()----> [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan()----> [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
x = [1,2,9,10, 16]
print("exp()---->", np.exp(x))          # e^x
print("exp2()---->", np.exp2(x))        # 2^x
print("power()---->", np.power(3, x))   # 3^x
print("log()---->", np.log(x))          # log自然對數
print("log2()---->", np.log2(x))        # 以2為基底的對數
print("log10()---->", np.log10(x))      # 以10為基底的對數


exp()----> [2.71828183e+00 7.38905610e+00 8.10308393e+03 2.20264658e+04
 8.88611052e+06]
exp2()----> [2.0000e+00 4.0000e+00 5.1200e+02 1.0240e+03 6.5536e+04]
power()----> [       3        9    19683    59049 43046721]
log()----> [0.         0.69314718 2.19722458 2.30258509 2.77258872]
log2()----> [0.         1.         3.169925   3.32192809 4.        ]
log10()----> [0.         0.30103    0.95424251 1.         1.20411998]


In [15]:
y = np.arange(1,6)
np.multiply.outer(y, y)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])