In [18]:
import numpy as np
array0 = np.zeros(10, dtype=int) #建立一個內容為0 長度為10的整數陣列
array1 = np.ones((3,5) ,dtype=float)  #建立一個內容為1 3x5 的浮點數陣列
array2 = np.full((4,2), 2.2) #建立一個內容為2.2 4x2 的浮點數陣列
array3 = np.arange(0,20,2) #建立一個依序填滿的陣列 0到20間隔為2
array4 = np.linspace(0,1,5) #建立一個5個值的陣列，在0到1間平均分布
array5 = np.random.random((3,3)) #建立一個3*3 陣列，在0到1間亂數值
array6 = np.random.normal(0,1,(3,3)) #建立一個3*3陣列，內容為常態分佈的亂數值 平均0，標準差1
array7 = np.random.randint(0,10,(3,3)) #建立一個3*3陣列，內容介於0到10的整數


array([[8, 9, 7],
       [1, 1, 1],
       [3, 3, 3]])

In [28]:
np.random.seed(0) #
x1 = np.random.randint(10, size=6)    #一維陣列
x2 = np.random.randint(10, size=(3,4))     #二維陣列
x3 = np.random.randint(10, size=(3,4,5))   #三維陣列
print("x3 ndim:     ", x3.ndim)                  #維度數量
print("x3 shape:    ", x3.shape)                 #每一個維度的大小
print("x3 size:     ", x3.size)                  #整個陣列的大小
print("x3 dtype:    ", x3.dtype)                 #整個陣列的資料型態
print("x3 itemsize: ", x3.itemsize, "bytes")     #陣列中元素的大小(位元組為單位)
print("x3 nbytes:   ", x3.nbytes, "bytes")       #整個陣列的大小(位元組為單位)  一般來說 nbytes = itemsize * size

x3 ndim:      3
x3 shape:     (3, 4, 5)
x3 size:      60
x3 dtype:     int32
x3 itemsize:  4 bytes
x3 nbytes:    240 bytes


In [33]:
print(x2)
x1[2]  #存取一維陣列
x1[-1]
x2[0,0] #存取多維陣列
x2[0,0] = 5 #修改元素值
x2[0,0]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


5

In [34]:
x4 = np.arange(10)

In [40]:
x4[:5]     # 前面5個元素
x4[5:]     # index5 之後的元素
x4[4:7]    # index 4~(7-1) 的元素
x4[::2]    # 間隔2的所有元素
x4[1::2]   # index1開始 間隔2的所有元素
x4[::-1]   # 反轉元素

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x2

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [47]:
x2[:2, :3]   #取得  2列        3欄
x2[:3, ::2]  #取得  3列        偶數欄
x2[:,0]      #取得 所有列      第(0+1)欄
x2[2,:]      #取得 第(2+1)列   所有欄


array([1, 6, 7, 7])

In [64]:
x = np.array([1,2,3])
x[np.newaxis,:]          # 透過newaxis建立(列)向量
x.reshape((3,1))         # 透過reshape建立欄向量
y = np.array([4,5,6])
np.concatenate([x,y])    # 串接陣列
np.vstack([x,y])         # 垂直串接
np.hstack([x,y])         # 水平串接
z = np.array([1,2,3,4,5,6,7,8,9])
z1,z2,z3 = np.split(z,[3,5])              # 分割3個陣列 [index 0~(3-1) ] [ index 3~(5-1)] [index (5~end)]
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.vsplit(z,[2])                          # 垂直分割
np.hsplit(z,[2])                          # 水平分割

[array([[1, 2],
        [4, 5],
        [7, 8]]), array([[3],
        [6],
        [9]])]