In [2]:
import numpy as np
x = np.array([-2,-1,0,1,-3])
abs(x)

array([2, 1, 0, 1, 3])

In [7]:
theta = np.linspace(0, np.pi, 3)  #建立一個角度的陣列
np.sin(theta)
np.cos(theta)
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [15]:
x = [1,2,9]
np.exp(x)
np.exp2(x)
np.power(3,x)
np.log(x)
np.log2(x)
np.log10(x)

array([0.        , 0.30103   , 0.95424251])

In [22]:
y = np.arange(1,6)
np.multiply.outer(y, y)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])