In [1]:
import numpy as np
L = np.random.random(100)
np.sum(L)

55.678448941378555

In [2]:
big_array = np.random.rand(1000000)
np.min(big_array), np.max(big_array)

(1.0612190134429156e-06, 0.9999999731690035)

In [4]:
%timeit min(big_array)
%timeit np.min(big_array)

57.5 ms ± 490 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
459 µs ± 6.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
m = np.random.random((3,4))
print(m)
m.sum()

[[0.79406235 0.91264286 0.80413291 0.6535581 ]
 [0.76413953 0.76026346 0.67266883 0.59105691]
 [0.43285696 0.65334366 0.41282604 0.33735136]]


7.7889029784449875

In [7]:
m.min(axis=0)

array([0.43285696, 0.65334366, 0.41282604, 0.33735136])

In [8]:
m.max(axis=1)

array([0.91264286, 0.76413953, 0.65334366])

In [12]:
a = np.array([0,1,2])
a + 5

array([5, 6, 7])

In [14]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
