In [1]:
import numpy as np
L = np.random.random(100)  #在0到1間亂數值取100個
np.sum(L)

47.407467980868724

In [19]:
m = np.random.random((3,4))
print(m)
print('column 加總', m.sum(axis=0)) #column加總
print('row 加總', m.sum(axis=1)) #row加總

[[0.90141178 0.44072501 0.5813923  0.06718993]
 [0.74907766 0.65631017 0.47611455 0.33805445]
 [0.79914804 0.9814414  0.23869758 0.10919935]]
column 加總 [2.44963747 2.07847657 1.29620443 0.51444374]
row 加總 [1.99071901 2.21955683 2.12848637]


In [7]:
print('0 軸加總', m.sum(axis=0)) #0軸加總
print('1 軸加總', m.sum(axis=1)) #1軸加總

0 軸加總 [1.56915755 2.607736   1.3662265  1.08113255]
1 軸加總 [2.31944909 1.90756859 2.39723492]


In [8]:
ironman_int = np.random.randint(0,10000,200) #在整數0~10000之間取值200個
print('min---->', np.min(ironman_int))
print('max---->', np.max(ironman_int))

min----> 1
max----> 9978


In [9]:
ironman_int_multi = np.random.randint(0,10000,(3,4)) #建立3*4的陣列，值介在整數0~10000之間
print('ironman_int_multi---->', ironman_int_multi)

print('ironman_int_multi.min(axis=0)----->', ironman_int_multi.min(axis=0))
print('ironman_int_multi.max(axis=1)----->', ironman_int_multi.max(axis=1))

ironman_int_multi----> [[5832 2201 5872 7898]
 [2839 9766  342 1527]
 [ 273 3194 4789 4585]]
ironman_int_multi.min(axis=0)-----> [ 273 2201  342 1527]
ironman_int_multi.max(axis=1)-----> [7898 9766 4789]


In [10]:
big_array = np.random.random(10000000) #在0到1間亂數值取10000000個
%timeit min(big_array)
%timeit np.min(big_array)

818 ms ± 186 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
14.1 ms ± 3.05 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
a = np.array([0,1,2])
a + 5

array([5, 6, 7])

In [12]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [13]:
x = np.array([1,2,3,4,5])
x>2

array([False, False,  True,  True,  True])

In [14]:
np.count_nonzero(x>2)

3

In [15]:
x = np.random.randint(10, size=(3,4))
print(x)
np.sum(x>5,axis = 1)

[[6 5 6 9]
 [0 1 3 0]
 [7 5 0 3]]


array([3, 0, 1])

In [16]:
np.all(x<8,axis = 0)

array([ True,  True,  True, False])

In [17]:
x = np.random.randint(10, size=(4,5))
print(x)
np.sum((x > 5) & (x <8))

[[3 7 0 5 6]
 [6 5 4 6 7]
 [5 4 3 7 0]
 [8 6 7 8 3]]


8