In [1]:
import numpy as np
L = np.random.random(100)  #在0到1間亂數值取100個
np.sum(L)

48.87105412779822

In [7]:
m = np.random.random((3,4))
m.sum()

5.977940837307657

In [5]:
ironman_int = np.random.randint(0,10000,200) #在整數0~10000之間取值200個
print('min---->', np.min(ironman_int))
print('max---->', np.max(ironman_int))

min----> 22
max----> 9946


In [12]:
ironman_int_multi = np.random.randint(0,10000,(3,4)) #建立3*4的陣列，值介在整數0~10000之間
print('ironman_int_multi---->', ironman_int_multi)

print('ironman_int_multi.min(axis=0)----->', ironman_int_multi.min(axis=0))
print('ironman_int_multi.max(axis=1)----->', ironman_int_multi.max(axis=1))

ironman_int_multi----> [[9931 4228 5996 3076]
 [2969 9102  374 1900]
 [5982 1051 9939 4320]]
ironman_int_multi.min(axis=0)-----> [2969 1051  374 1900]
ironman_int_multi.max(axis=1)-----> [9931 9102 9939]


In [6]:
big_array = np.random.random(10000000) #在0到1間亂數值取10000000個
%timeit min(big_array)
%timeit np.min(big_array)

612 ms ± 23.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.38 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
a = np.array([0,1,2])
a + 5

array([5, 6, 7])

In [14]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [14]:
x = np.array([1,2,3,4,5])
x>2

array([False, False,  True,  True,  True])

In [15]:
np.count_nonzero(x>2)

3

In [16]:
x = np.random.randint(10, size=(3,4))
print(x)
np.sum(x>5,axis = 1)

[[0 7 2 8]
 [8 9 3 9]
 [8 0 2 1]]


array([2, 3, 1])

In [18]:
np.all(x<8,axis = 0)

array([False, False,  True, False])

In [19]:
x = np.random.randint(10, size=(4,5))
print(x)
np.sum((x > 5) & (x <8))

[[4 2 2 4 0]
 [4 7 0 1 4]
 [9 1 7 6 9]
 [4 3 7 7 8]]


5