In [1]:
import numpy as np
x = np.random.randint(0,100,size = 10)
print('x----------->',x)


x-----------> [66 74 84 13 37 83 58 90 84 23]


In [2]:
[x[0],x[3],x[2],x[6]]

[66, 13, 84, 58]

In [3]:
ironman = np.array([
    [0,3],
    [2,6]
])
x[ironman]

array([[66, 13],
       [84, 58]])

In [8]:
y = np.random.randint(0,100,(3,4))
print('y-------->',y)
row = np.array([0,1,2])
col = np.array([2,1,3])
print('y[row,col]----->',y[row,col])

y--------> [[65 76 49 29]
 [24 96 13 20]
 [91 58 37 24]]
y[row,col]-----> [49 96 24]


In [9]:

newRow = row[:, np.newaxis]
print('newRow----->',newRow)
print('y[newRow,col]----->',y[newRow,col])


newRow-----> [[0]
 [1]
 [2]]
y[newRow,col]-----> [[49 76 29]
 [13 96 20]
 [37 58 24]]


In [11]:
x = np.random.randint(0,100,size = 10)
print('x--------------->',x)
i = np.array([2,1,5,7])
print('i--------------->',i)
x[i] = 33
print('x--------------->',x)

x---------------> [91 38 11 54 82 67 63  4  7 34]
i---------------> [2 1 5 7]
x---------------> [91 33 33 54 82 33 63 33  7 34]


In [12]:
x = np.random.randint(0,100,size = 10)
print('x--------------->',x)
x.sort()
print('x--------------->',x)

x---------------> [15 85 51 98 65 43 78 61 85 17]
x---------------> [15 17 43 51 61 65 78 85 85 98]


In [13]:
x = np.random.randint(0,100,size = 5)
print('x--------------->',x)
print('np.argsort(x)--------------->',np.argsort(x))

x---------------> [40 22 91 18 74]
np.argsort(x)---------------> [3 1 0 4 2]


In [14]:
x = np.random.randint(0,100,(4,4))
print('x--------------->',x)
np.sort(x,axis=0)

x---------------> [[72 22 23 27]
 [50 39 78  3]
 [91 27 12 47]
 [75 75 78 94]]


array([[50, 22, 12,  3],
       [72, 27, 23, 27],
       [75, 39, 78, 47],
       [91, 75, 78, 94]])

In [15]:
x = np.random.randint(0,50,size=10)
print('x--------------->',x)
np.partition(x,4)

x---------------> [48 29 38 24  9 46  6 29  3 21]


array([ 6,  9,  3, 21, 24, 29, 29, 46, 38, 48])

In [16]:
team =np.zeros(4, dtype={'names':('name','number','team'),'formats':('U10','i2','U10')})
print('team.dtype------------>',team.dtype)
team['name'] =['彭政閔','林智勝','蘇偉達','陽耀勳']
team['number'] = [23,32,96,23]
team['team'] = ['兄弟象','兄弟象','兄弟象','lamigo']
print('team------------>',team)

team.dtype------------> [('name', '<U10'), ('number', '<i2'), ('team', '<U10')]
team------------> [('彭政閔', 23, '兄弟象') ('林智勝', 32, '兄弟象') ('蘇偉達', 96, '兄弟象')
 ('陽耀勳', 23, 'lamigo')]


In [16]:
print(team['number'])

[23 32 96 23]
